# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EodAdministators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': True,
                'db_table': 'eod_administators',
            },
        ),
        migrations.CreateModel(
            name='ExoObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=45)),
                ('type', models.IntegerField(db_column='Type')),
                ('epoch', models.DecimalField(db_column='Epoch', decimal_places=9, max_digits=16)),
                ('epoch_time_standard', models.CharField(db_column='Epoch_Time_Standard', max_length=7)),
                ('period', models.DecimalField(db_column='Period', decimal_places=6, max_digits=9)),
                ('transit_duration', models.DecimalField(db_column='Transit_Duration', decimal_places=6, max_digits=7)),
                ('orbit_inclination', models.DecimalField(db_column='Orbit_Inclination', decimal_places=2, max_digits=4)),
                ('ephemeris_source', models.CharField(blank=True, db_column='Ephemeris_Source', max_length=45, null=True)),
                ('eod_administators', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.EodAdministators')),
            ],
            options={
                'managed': True,
                'db_table': 'EXO_OBJECTS',
            },
        ),
        migrations.CreateModel(
            name='ExoObjectsHasStars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_star_name', models.CharField(db_column='STARS_Star_Name', max_length=11)),
                ('exo_objects', models.ForeignKey(db_column='EXO-OBJECTS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoObjects')),
            ],
            options={
                'managed': True,
                'db_table': 'EXO-OBJECTS_has_STARS',
            },
        ),
        migrations.CreateModel(
            name='ExoplanetExoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jd', models.DecimalField(blank=True, db_column='JD', decimal_places=6, max_digits=13, null=True)),
                ('hjd_utc', models.DecimalField(blank=True, db_column='HJD_UTC', decimal_places=6, max_digits=13, null=True)),
                ('bjd_tdb', models.DecimalField(blank=True, db_column='BJD_TDB', decimal_places=6, max_digits=13, null=True)),
                ('differential_magnitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('mag_uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('detrend_1', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('detrend_2', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('detrend_3', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('detrend_4', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('added_date', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'exoplanet.exo_data',
            },
        ),
        migrations.CreateModel(
            name='ExoplanetExoObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auid', models.CharField(blank=True, db_column='AUID', max_length=11, null=True)),
                ('star_name', models.CharField(blank=True, max_length=45, null=True)),
                ('exoplanet_name', models.CharField(blank=True, max_length=45, null=True)),
                ('obscode', models.CharField(blank=True, max_length=5, null=True)),
                ('software', models.CharField(blank=True, max_length=45, null=True)),
                ('obstype', models.IntegerField(blank=True, null=True)),
                ('secondary_stars', models.CharField(blank=True, max_length=45, null=True)),
                ('secondary_obscodes', models.CharField(blank=True, max_length=50, null=True)),
                ('exposure_time', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('binning', models.CharField(blank=True, max_length=3, null=True)),
                ('filter', models.CharField(blank=True, max_length=5, null=True)),
                ('reference_star_filename', models.CharField(blank=True, max_length=45, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detrend_name_1', models.CharField(blank=True, max_length=45, null=True)),
                ('detrend_name_2', models.CharField(blank=True, max_length=45, null=True)),
                ('detrend_name_3', models.CharField(blank=True, max_length=45, null=True)),
                ('detrend_name_4', models.CharField(blank=True, max_length=45, null=True)),
                ('priors', models.CharField(blank=True, max_length=45, null=True)),
                ('results', models.CharField(blank=True, max_length=45, null=True)),
                ('valflag', models.CharField(blank=True, max_length=1, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'exoplanet.exo_observation',
            },
        ),
        migrations.CreateModel(
            name='ExoplanetNames',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('auid', models.CharField(blank=True, db_column='AUID', max_length=11, null=True)),
                ('alias_1', models.CharField(blank=True, max_length=45, null=True)),
                ('alias_2', models.CharField(blank=True, max_length=45, null=True)),
                ('alias_3', models.CharField(blank=True, max_length=45, null=True)),
                ('alias_4', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'exoplanet.names',
            },
        ),
        migrations.CreateModel(
            name='ExoplanetSecondaryObscodeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obscode', models.CharField(blank=True, max_length=5, null=True)),
                ('added_date', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('exoplanet_exo_observation', models.ForeignKey(db_column='exoplanet.exo_observation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoplanetExoObservation')),
            ],
            options={
                'managed': True,
                'db_table': 'exoplanet.secondary_obscode_link',
            },
        ),
        migrations.CreateModel(
            name='ExoplanetSecondaryStarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auid', models.CharField(blank=True, db_column='AUID', max_length=11, null=True)),
                ('added_date', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('exoplanet_exo_observation', models.ForeignKey(db_column='exoplanet.exo_observation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoplanetExoObservation')),
            ],
            options={
                'managed': True,
                'db_table': 'exoplanet.secondary_star_link',
            },
        ),
        migrations.CreateModel(
            name='HqPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obscode', models.CharField(max_length=4)),
            ],
            options={
                'managed': True,
                'db_table': 'hq_person',
            },
        ),
        migrations.CreateModel(
            name='HqPersonEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=45)),
                ('telescope', models.CharField(max_length=45)),
                ('spectrograph', models.CharField(blank=True, max_length=45, null=True)),
                ('rpow', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('aperture', models.IntegerField()),
                ('fl', models.IntegerField()),
                ('imaging_camera', models.CharField(max_length=45)),
                ('gain', models.DecimalField(decimal_places=3, max_digits=5)),
                ('readout_noise', models.IntegerField()),
                ('dark_current', models.DecimalField(decimal_places=3, max_digits=4)),
                ('linearity', models.IntegerField()),
                ('x_photosites', models.IntegerField()),
                ('y_photosites', models.IntegerField()),
                ('x_photosite_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('y_photosite_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('obsolete', models.IntegerField()),
                ('hq_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPerson')),
            ],
            options={
                'managed': True,
                'db_table': 'hq_person_equipment',
            },
        ),
        migrations.CreateModel(
            name='HqPersonSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=45)),
                ('sitelat', models.FloatField()),
                ('sitelong', models.FloatField()),
                ('sitealt', models.IntegerField()),
                ('obsolete', models.IntegerField()),
                ('hq_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPerson')),
            ],
            options={
                'managed': True,
                'db_table': 'hq_person_site',
            },
        ),
        migrations.CreateModel(
            name='LimbDarkeningCoefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldc_id', models.CharField(db_column='LDC_ID', max_length=45)),
                ('filter', models.CharField(db_column='Filter', max_length=5)),
                ('u1', models.DecimalField(db_column='U1', decimal_places=9, max_digits=10)),
                ('u2', models.DecimalField(db_column='U2', decimal_places=9, max_digits=10)),
                ('exo_objects', models.ForeignKey(db_column='EXO_OBJECTS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoObjects')),
            ],
            options={
                'managed': True,
                'db_table': 'LIMB_DARKENING_COEFFICIENTS',
            },
        ),
        migrations.CreateModel(
            name='LinkExoObjectsAndVsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exo_objects', models.ForeignKey(db_column='EXO_OBJECTS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoObjects')),
            ],
            options={
                'managed': True,
                'db_table': 'LINK_EXO_OBJECTS_and_VSX',
            },
        ),
        migrations.CreateModel(
            name='LinkObservationsAndHqPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hq_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPerson')),
            ],
            options={
                'managed': True,
                'db_table': 'LINK_OBSERVATIONS_and_hq_person',
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('observation_id', models.CharField(blank=True, max_length=45, null=True)),
                ('begin_time', models.DateTimeField(db_column='Begin_Time')),
                ('meridian_flip_flag', models.IntegerField(db_column='Meridian_Flip_Flag')),
                ('meridian_flip_time', models.DateTimeField(blank=True, db_column='Meridian_Flip_Time', null=True)),
                ('transit_time_standard', models.CharField(db_column='Transit_Time_Standard', max_length=7)),
                ('predicted_ingress', models.DecimalField(db_column='Predicted_Ingress', decimal_places=9, max_digits=16)),
                ('predicted_egress', models.DecimalField(db_column='Predicted_Egress', decimal_places=9, max_digits=16)),
                ('bias_files_zip_filename', models.CharField(blank=True, db_column='Bias_Files_Zip_Filename', max_length=45, null=True)),
                ('dark_files_zip_filename', models.CharField(blank=True, db_column='Dark_Files_Zip_Filename', max_length=45, null=True)),
                ('flat_files_zip_filename', models.CharField(blank=True, db_column='Flat_Files_Zip_Filename', max_length=45, null=True)),
                ('flat_dark_files_zip_filename', models.CharField(blank=True, db_column='Flat_Dark_Files_Zip_Filename', max_length=45, null=True)),
                ('results_depth', models.DecimalField(blank=True, db_column='Results_Depth', decimal_places=9, max_digits=10, null=True)),
                ('results_a_r_field', models.DecimalField(blank=True, db_column='Results_a/R*', decimal_places=9, max_digits=11, null=True)),
                ('results_tc', models.DecimalField(blank=True, db_column='Results_Tc', decimal_places=9, max_digits=16, null=True)),
                ('results_orbital_incl', models.DecimalField(blank=True, db_column='Results_Orbital_Incl', decimal_places=6, max_digits=7, null=True)),
                ('results_rms', models.DecimalField(blank=True, db_column='Results_RMS', decimal_places=6, max_digits=7, null=True)),
                ('detrend_airmass', models.IntegerField(blank=True, db_column='Detrend_Airmass', null=True)),
                ('detrend_meridian_flip', models.IntegerField(blank=True, db_column='Detrend_Meridian_Flip', null=True)),
                ('detrend_target_width', models.IntegerField(blank=True, db_column='Detrend_Target_Width', null=True)),
                ('target_sky_cnts_pixel', models.IntegerField(blank=True, db_column='Target_Sky_Cnts/Pixel', null=True)),
                ('detrend_target_x_fits_field', models.IntegerField(blank=True, db_column='Detrend_Target_X(FITS)', null=True)),
                ('detrend_target_y_fits_field', models.IntegerField(blank=True, db_column='Detrend_Target_Y(FITS)', null=True)),
                ('detrend_total_comp_star_cnts', models.IntegerField(blank=True, db_column='Detrend_Total_Comp_Star_Cnts', null=True)),
                ('detrend_jd_utc', models.IntegerField(blank=True, db_column='Detrend_JD_UTC', null=True)),
                ('detrend_hjd_utc', models.IntegerField(blank=True, db_column='Detrend_HJD_UTC', null=True)),
                ('detrend_bjd_utc', models.IntegerField(blank=True, db_column='Detrend_BJD_UTC', null=True)),
                ('detrend_bjd_tdb', models.IntegerField(blank=True, db_column='Detrend_BJD_TDB', null=True)),
                ('detrend_ccd_temp', models.IntegerField(blank=True, db_column='Detrend_CCD_Temp', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('exo_objects', models.ForeignKey(db_column='EXO_OBJECTS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoObjects')),
                ('hq_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPerson')),
                ('hq_person_equipment_equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPersonEquipment')),
                ('hq_person_site_site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPersonSite')),
            ],
            options={
                'managed': True,
                'db_table': 'OBSERVATIONS',
            },
        ),
        migrations.CreateModel(
            name='ObservationSegments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('segment_number', models.IntegerField(db_column='Segment_Number')),
                ('begin_time', models.DateTimeField(db_column='Begin_Time')),
                ('binning', models.CharField(db_column='Binning', max_length=3)),
                ('pixel_scale', models.DecimalField(db_column='Pixel_Scale', decimal_places=2, max_digits=4)),
                ('exposure_time', models.DecimalField(db_column='Exposure_Time', decimal_places=1, max_digits=5)),
                ('filter_used', models.CharField(db_column='Filter_Used', max_length=5)),
                ('fwhm', models.DecimalField(db_column='FWHM', decimal_places=1, max_digits=3)),
                ('measurements_zip_filename', models.CharField(blank=True, db_column='Measurements_Zip_Filename', max_length=45, null=True)),
                ('observations', models.ForeignKey(db_column='OBSERVATIONS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.Observations')),
            ],
            options={
                'managed': True,
                'db_table': 'OBSERVATION_SEGMENTS',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetCompStar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('star_number', models.IntegerField(db_column='Star_Number')),
                ('target_or_comp', models.IntegerField(db_column='Target_or_Comp')),
                ('aperture_radius', models.IntegerField(db_column='Aperture_Radius')),
                ('annulus_inner_radius', models.IntegerField(db_column='Annulus_Inner_Radius')),
                ('annulus_outer_radius', models.IntegerField(db_column='Annulus_Outer_Radius')),
                ('star_ra', models.CharField(blank=True, db_column='Star_RA', max_length=11, null=True)),
                ('star_dec', models.CharField(blank=True, db_column='Star_DEC', max_length=11, null=True)),
                ('observation_segments', models.ForeignKey(db_column='OBSERVATION_SEGMENTS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ObservationSegments')),
            ],
            options={
                'managed': True,
                'db_table': 'TARGET_COMP_STAR',
            },
        ),
        migrations.CreateModel(
            name='Vsd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('auid', models.CharField(db_column='AUID', max_length=11)),
            ],
            options={
                'managed': True,
                'db_table': 'VSD',
            },
        ),
        migrations.CreateModel(
            name='Vsx',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('auid', models.CharField(db_column='AUID', max_length=11)),
                ('rstar', models.DecimalField(blank=True, db_column='Rstar', decimal_places=3, max_digits=5, null=True)),
                ('teff', models.IntegerField(blank=True, db_column='Teff', null=True)),
                ('fe_h', models.DecimalField(blank=True, db_column='Fe/H', decimal_places=2, max_digits=4, null=True)),
                ('log_g_field', models.DecimalField(blank=True, db_column='log(g)', decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'VSX',
            },
        ),
        migrations.CreateModel(
            name='WebDjangoHqPersonEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(blank=True, max_length=45, null=True)),
                ('telescope', models.CharField(blank=True, max_length=45, null=True)),
                ('spectrograph', models.CharField(blank=True, max_length=45, null=True)),
                ('rpow', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('aperture', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.IntegerField(blank=True, null=True)),
                ('imaging_camera', models.CharField(blank=True, max_length=45, null=True)),
                ('gain', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('readout_noise', models.IntegerField(blank=True, null=True)),
                ('dark_current', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('linearity', models.IntegerField(blank=True, null=True)),
                ('x_photosites', models.IntegerField(blank=True, null=True)),
                ('y_photosites', models.IntegerField(blank=True, null=True)),
                ('x_photosite_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('y_photosite_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('obsolete', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'web_django.hq_person_equipment',
            },
        ),
        migrations.CreateModel(
            name='WebDjanjoHqPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
                'db_table': 'web_djanjo.hq_person',
            },
        ),
        migrations.CreateModel(
            name='WebDjanjoHqPersonSite',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(blank=True, max_length=45, null=True)),
                ('sitelat', models.FloatField(blank=True, null=True)),
                ('sitelong', models.FloatField(blank=True, null=True)),
                ('sitealt', models.IntegerField(blank=True, null=True)),
                ('obsolete', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('web_djanjo_hq_person', models.ForeignKey(db_column='web_djanjo.hq_person_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.WebDjanjoHqPerson')),
            ],
            options={
                'managed': True,
                'db_table': 'web_djanjo.hq_person_site',
            },
        ),
        migrations.AddField(
            model_name='webdjangohqpersonequipment',
            name='web_djanjo_hq_person',
            field=models.ForeignKey(db_column='web_djanjo.hq_person_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.WebDjanjoHqPerson'),
        ),
        migrations.AddField(
            model_name='targetcompstar',
            name='vsd',
            field=models.ForeignKey(db_column='VSD_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.Vsd'),
        ),
        migrations.AddField(
            model_name='linkobservationsandhqperson',
            name='observations',
            field=models.ForeignKey(db_column='OBSERVATIONS_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.Observations'),
        ),
        migrations.AddField(
            model_name='linkexoobjectsandvsx',
            name='vsx',
            field=models.ForeignKey(db_column='VSX_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.Vsx'),
        ),
        migrations.AddField(
            model_name='exoplanetsecondaryobscodelink',
            name='web_djanjo_hq_person',
            field=models.ForeignKey(db_column='web_djanjo.hq_person_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.WebDjanjoHqPerson'),
        ),
        migrations.AddField(
            model_name='exoplanetexoobservation',
            name='exoplanet_names',
            field=models.ForeignKey(db_column='exoplanet.names_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoplanetNames'),
        ),
        migrations.AddField(
            model_name='exoplanetexoobservation',
            name='web_django_hq_person_equipment',
            field=models.ForeignKey(db_column='web-django.hq_person_equipment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.WebDjangoHqPersonEquipment'),
        ),
        migrations.AddField(
            model_name='exoplanetexoobservation',
            name='web_djanjo_hq_person_site',
            field=models.ForeignKey(db_column='web_djanjo.hq_person_site_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.WebDjanjoHqPersonSite'),
        ),
        migrations.AddField(
            model_name='exoplanetexodata',
            name='exoplanet_exo_observation',
            field=models.ForeignKey(db_column='exoplanet.exo_observation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.ExoplanetExoObservation'),
        ),
        migrations.AddField(
            model_name='exoobjectshasstars',
            name='stars',
            field=models.ForeignKey(db_column='STARS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.Vsx'),
        ),
        migrations.AddField(
            model_name='eodadministators',
            name='hq_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exosite.HqPerson'),
        ),
        migrations.AlterUniqueTogether(
            name='linkobservationsandhqperson',
            unique_together=set([('observations', 'hq_person')]),
        ),
        migrations.AlterUniqueTogether(
            name='linkexoobjectsandvsx',
            unique_together=set([('exo_objects', 'vsx')]),
        ),
        migrations.AlterUniqueTogether(
            name='exoobjectshasstars',
            unique_together=set([('exo_objects', 'stars', 'stars_star_name')]),
        ),
    ]
