# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exosite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exoplanetexodata',
            name='jd',
        ),
        migrations.AddField(
            model_name='exoplanetexodata',
            name='jd_utc',
            field=models.DecimalField(blank=True, db_column='JD_UTC', decimal_places=6, max_digits=13, null=True),
        ),
    ]
