# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exosite', '0002_auto_20170521_2242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkobservationsandhqperson',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='linkobservationsandhqperson',
            name='hq_person',
        ),
        migrations.RemoveField(
            model_name='linkobservationsandhqperson',
            name='observations',
        ),
        migrations.DeleteModel(
            name='LinkObservationsAndHqPerson',
        ),
    ]
