# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exosite', '0003_auto_20170527_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eodadministators',
            name='hq_person',
        ),
        migrations.RemoveField(
            model_name='exoobjects',
            name='eod_administators',
        ),
        migrations.AlterUniqueTogether(
            name='exoobjectshasstars',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='exoobjectshasstars',
            name='exo_objects',
        ),
        migrations.RemoveField(
            model_name='exoobjectshasstars',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='hqpersonequipment',
            name='hq_person',
        ),
        migrations.RemoveField(
            model_name='hqpersonsite',
            name='hq_person',
        ),
        migrations.RemoveField(
            model_name='limbdarkeningcoefficients',
            name='exo_objects',
        ),
        migrations.AlterUniqueTogether(
            name='linkexoobjectsandvsx',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='linkexoobjectsandvsx',
            name='exo_objects',
        ),
        migrations.RemoveField(
            model_name='linkexoobjectsandvsx',
            name='vsx',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='exo_objects',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='hq_person',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='hq_person_equipment_equipment',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='hq_person_site_site',
        ),
        migrations.RemoveField(
            model_name='observationsegments',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='targetcompstar',
            name='observation_segments',
        ),
        migrations.RemoveField(
            model_name='targetcompstar',
            name='vsd',
        ),
        migrations.DeleteModel(
            name='EodAdministators',
        ),
        migrations.DeleteModel(
            name='ExoObjects',
        ),
        migrations.DeleteModel(
            name='ExoObjectsHasStars',
        ),
        migrations.DeleteModel(
            name='HqPerson',
        ),
        migrations.DeleteModel(
            name='HqPersonEquipment',
        ),
        migrations.DeleteModel(
            name='HqPersonSite',
        ),
        migrations.DeleteModel(
            name='LimbDarkeningCoefficients',
        ),
        migrations.DeleteModel(
            name='LinkExoObjectsAndVsx',
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
        migrations.DeleteModel(
            name='ObservationSegments',
        ),
        migrations.DeleteModel(
            name='TargetCompStar',
        ),
        migrations.DeleteModel(
            name='Vsd',
        ),
        migrations.DeleteModel(
            name='Vsx',
        ),
    ]
